# Term compability
set -g default-terminal "tmux-256color"
set-option -gas terminal-overrides "*:Tc" # true color support
set-option -gas terminal-overrides "*:RGB" # true color support
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

# Set the prefixe to <C-x>
unbind C-b
set-option -g prefix C-x 

# Easy config reload
bind-key r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."

# Movements through panels
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Switch windows
bind -n C-Left  previous-window
bind -n C-Right next-window

# Enable full mouse support
set -g mouse on

# Key-bindings for copy-paste
setw -g mode-keys vi
unbind p
bind p paste-buffer
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

# Key-bindings for copy-paste
setw -g mode-keys vi
unbind p
bind p paste-buffer
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

# Reorder windows with CTRL+SHIFT+Arrow
bind-key -n C-S-Left swap-window -t -1
bind-key -n C-S-Right swap-window -t +1

# Set the base-index to 1
set -g base-index 1
setw -g pane-base-index 1

# Windows index get reordered on delete
set-option -g renumber-windows on

# Split panes
bind-key h split-window -v
bind-key v split-window -h
unbind '"'
unbind %

# Disable bell
setw -g monitor-bell off

# Status bar options
set-option -g status-position top

#Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'

set -g @dracula-show-powerline true
set -g @dracula-plugins "git cpu-usage ram-usage battery time" 
set -g @dracula-refresh-rate 5
set -g @dracula-show-left-icon session
set -g @dracula-cpu-usage-label ""
set -g @dracula-ram-usage-label ""
set -g @dracula-show-empty-plugins true
set -g @dracula-battery-label "⚡"
set -g @dracula-military-time true
set -g @dracula-show-timezone false
set -g @dracula-battery-colors "yellow gray"

run '~/.tmux/plugins/tpm/tpm'
