# Initial setup
set -g default-terminal xterm-256color

# Set the prefixe to <C-j>
unbind C-b
set-option -g prefix C-j 

# Easy config reload
bind-key r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."

# Movements through panels
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Switch windows
bind -n C-Left  previous-window
bind -n C-Right next-window

# Resize panes
bind -n S-Left resize-pane -L 5
bind -n S-Right resize-pane -R 5
bind -n S-Up resize-pane -U 5
bind -n S-Down resize-pane -D 5

# Enable full mouse support
set -g mouse on

# Set the base-index to 1
set -g base-index 1
setw -g pane-base-index 1

# Windows index get reordered on delete
set-option -g renumber-windows on

# Split panes
bind-key h split-window -v
bind-key v split-window -h
unbind '"'
unbind %

# Disable bell
setw -g monitor-bell off

# Status bar options
set-option -g status-position top

#Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'

set -g @dracula-show-powerline true
set -g @dracula-plugins "git cpu-usage ram-usage battery time" 
set -g @dracula-refresh-rate 5
set -g @dracula-show-left-icon session
set -g @dracula-cpu-usage-label ""
set -g @dracula-ram-usage-label ""
set -g @dracula-show-empty-plugins true
set -g @dracula-battery-label "⚡"
set -g @dracula-military-time true
set -g @dracula-show-timezone false
set -g @dracula-battery-colors "yellow gray"

run '~/.tmux/plugins/tpm/tpm'
